### PR TITLE
Increase the frequency of the walking-controller to 500Hz

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This requires https://github.com/ami-iit/robots-configuration/pull/20

### CODE REVIEW

**Comment by S-Dafarra** [comment]
@GiulioRomualdi should we proceed in merging this?

**Comment by GiulioRomualdi** [comment]
It's actually integrated in https://github.com/robotology/walking-controllers/pull/132

**Comment by S-Dafarra** [comment]
SInce we are not sure if #132 will get merged, does it make sense to proceed with this anyhow?

**Comment by GiulioRomualdi** [comment]
Closing in favor of https://github.com/robotology/walking-controllers/pull/136/

**Pull request closed without merging**
