### PR TITLE
Added weight retrieval function

### PR DESCRIPTION
**Pull request by bemilio**
The [ TrajectoryGenerator](https://github.com/robotology/walking-controllers/blob/devel/src/TrajectoryPlanner/include/WalkingControllers/TrajectoryPlanner/TrajectoryGenerator.h) is missing a method to get the weight in left and right feet that are instead present in the [element](https://github.com/dic-iit/element_dcm-walking/blob/c1936dd5d31b5bbe19d67869b310533017f9a95b/src/TrajectoryPlanner/include/WalkingControllers/TrajectoryPlanner/TrajectoryGenerator.h#L243) . I added this functionality, copying it from the element

### CODE REVIEW

**Comment by bemilio** [comment]
> There are a lot of small changes which are not "new". Can you try to remove all the small modifications and keep only those that you actually want to merge? Otherwise reviewing this PR is complicated.
> 
> As an example, you modified
> 
> ```
> iDynTree::Vector2 m_referencePointDistance; /**< Vector between the center of the unicycle and the point that has to be reach the goal. */
> ```
> 
> into
> 
> ```
>   iDynTree::Vector2 m_referencePointDistance; /**< Vector between the center of
>                                                  the unicycle and the point that
>                                                  has to be reach the goal. */
> ```
> 
> The problem is that this screws up the git diff.

Addressed

**Comment by S-Dafarra** [comment]
@GiulioRomualdi can we merge this?

**Comment by GiulioRomualdi** [comment]
@bemilio  before merging can you update the `CHANGELOG.md` file adding a line that summarizes the change that you added

**Comment by bemilio** [comment]
Done

**Comment by GiulioRomualdi** [comment]
Merging!

**Pull request merged**
