### PR TITLE
Fix YARP_DATA_DIRS and setGoal in readme

### PR DESCRIPTION
**Pull request by S-Dafarra**
The configuration files are save in the ``ICUBContrib`` folders. See https://github.com/robotology/walking-controllers/blob/56071b8ca640800667bb81b185c58307c7303ca7/src/WalkingModule/app/CMakeLists.txt#L45

### CODE REVIEW

**Comment by S-Dafarra** [comment]
cc @xela-95

**Comment by traversaro** [comment]
Proposal: instead of fixing the docs, can't we just change `ICUBCONTRIB_ROBOTS_INSTALL_DIR` to `YARP_ROBOTS_INSTALL_DIR`?

This is consistent with other projects (https://github.com/robotology/whole-body-estimators/blob/5fb9aeeb1cc9282189eee11754c78f685814ed9f/devices/baseEstimatorV1/app/CMakeLists.txt#L23, https://github.com/robotology/walking-teleoperation/blob/a4b0ef4ac1fe22beadbaa17354a949ee46a7f704/app/CMakeLists.txt#L23, https://github.com/ami-iit/bipedal-locomotion-framework/blob/a9f2166329ec9411f283ae9b6a578b8197d2fd50/devices/YarpRobotLoggerDevice/app/CMakeLists.txt#L9), would remove the dependency on ICUBcontrib, and work out of the box if one installs walking-controllers in the same directory of yarp (as it happens when one installs in a conda prefix of in the robotology-superbuild install dir).

**Comment by S-Dafarra** [comment]
> Proposal: instead of fixing the docs, can't we change `ICUBCONTRIB_ROBOTS_INSTALL_DIR` to `YARP_ROBOTS_INSTALL_DIR` and other related libraries?

Seems like a good idea. I am trying to remember why we picked `ICUBCONTRIB_ROBOTS_INSTALL_DIR` in the first place, but I think it was just to mix it with the robot-specific configuration files, but I don't think this is really necessary. I also checked the various scripts we have in the robot setup, but this should not cause any issue. @GiulioRomualdi anything against it?

**Comment by traversaro** [comment]
By the way, I do not think the discussion needs to block the PR, for sure the PR is doing the right thing.

**Review by traversaro — APPROVED** [review]

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
> Proposal: instead of fixing the docs, can't we change `ICUBCONTRIB_ROBOTS_INSTALL_DIR` to `YARP_ROBOTS_INSTALL_DIR` and other related libraries?

Yes! I agree

**Pull request merged**
