### PR TITLE
Add include Position.h

### LINKED ISSUE #79: Problem when including ZMP controller
@bemilio noticed that:

---
If I indlude the ZMP controller:

`#include <WalkingControllers/SimplifiedModelControllers/ZMPController.h>`
And then I call the method `setFeedback` 
I get the error 

```
/home/emilio/Repositories/robotology-superbuild/build/install/include/WalkingControllers/SimplifiedModelControllers/ZMPController.h:83:42: error: ‘Position’ in namespace ‘iDynTree’ does not name a type
                          const iDynTree::Position& comFeedback);

```

This is solved by adding in `robotology-superbuild/robotology/walking-controllers/src/SimplifiedModelControllers/include/WalkingControllers/SimplifiedModelControllers/ZMPController.h` 

the line: 
```
#include <iDynTree/Core/Position.h>
```

### PR DESCRIPTION
**Pull request by Giulero**
This PR should fix #79

### CODE REVIEW

**Comment by traversaro** [comment]
@GiulioRomualdi we may want to merge this before releasing 0.4.1 ?

**Comment by GiulioRomualdi** [comment]
@Giulero thank you for the PR :smile: 

Could you update the `CHANGELOG.md`?

**Comment by Giulero** [comment]
ehmmmm

**Comment by Giulero** [comment]
Fixed :)

**Comment by GiulioRomualdi** [comment]
Thank you @Giulero

**Pull request merged**
