### PR TITLE
Merge Devel into Master

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
The `devel` branch has been extensively tested in the latest months and it can be now merged on the master branch. 
The main changes are:
1. Implementation of the `RetargetingClient`: the user can now switch between the retargeting and joypad control
2. The controller required at least the version 0.4.0 of `osqp-eigen`
3. The configuration files are now installed in `ICUBContrib` folder

I add a tag for the previous version of the application: https://github.com/robotology/walking-controllers/releases/tag/v0.1.0

This PR is currently blocking #43

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Make sure to bump the version!

**Comment by GiulioRomualdi** [comment]
> Make sure to bump the version!

Do you mean in the cmake file?

**Comment by S-Dafarra** [comment]
I just realized we don't have a version number for this repo. Maybe it is worth adding it :thinking:

**Comment by GiulioRomualdi** [comment]
Yes, I agree. Since I considered master `0.1.0` what do you think about `0.2.0`?

**Comment by S-Dafarra** [comment]
Ok for me! For ``devel`` I would follow the [``YARP`` versioning](https://github.com/robotology/yarp/blob/master/.github/CONTRIBUTING.md#terminology).

**Pull request merged**
