### PR TITLE
Tune the low level gains of the iCubGazeboV3

### PR DESCRIPTION
**Pull request by mebbaid**
after yesterdays issues during the meeting, now with a clean build, using master or devel, and with those pidparams, it seems the simulation is more reproducible and stable than before (see attached video)

https://user-images.githubusercontent.com/36491318/153573524-4c82d5c2-8ec1-4c3c-a52f-97926c7b89c6.MP4

.

### CODE REVIEW

**Review by S-Dafarra — APPROVED** [review]
Awesome!

**Comment by S-Dafarra** [comment]
Actually, I think that we can target directly ``master``, right @GiulioRomualdi?

**Comment by GiulioRomualdi** [comment]
Nice! At this point isnt better to commits those gains directly in icub models?

**Comment by mebbaid** [comment]
> Nice! At this point isn't better to commits those gains directly in icub models?

Ok, if you think it is better to commit there then sure. The guys from HSP were installing everything individually and not through the superbuild, so that makes sense.

**Comment by mebbaid** [comment]
> Nice! At this point isnt better to commits those gains directly in icub models?

Let me know if [this PR](https://github.com/robotology/icub-models/pull/126) is corresponding to what you suggested.

**Comment by GiulioRomualdi** [comment]
Hi @mebbaid did you open a PR in icub-models-generator as suggested by @traversaro in  https://github.com/robotology/icub-models/pull/126? 

Can I close this PR?

**Comment by mebbaid** [comment]
Hi @GiulioRomualdi 

The suggested PR is not opened yet. The halt is due to [me not being able to verify the same good behaviour in a different machine used by the HSP team](https://github.com/robotology/walking-controllers/issues/107#issuecomment-1040463950). So I am spending sometime tuning and was going to close once the other PR is opened.

**Comment by mebbaid** [comment]
Opened a corresponding PR in `icub-model-generators` ,  see [this PR](https://github.com/robotology/icub-models-generator/pull/219).

Closing


> Hi @GiulioRomualdi
> 
> The suggested PR is not opened yet. The halt is due to [me not being able to verify the same good behaviour in a different machine used by the HSP team](https://github.com/robotology/walking-controllers/issues/107#issuecomment-1040463950). So I am spending sometime tuning and was going to close once the other PR is opened.

**Pull request closed without merging**
