### PR TITLE
Using the feetYawDelta and the slowWhenBackwardFactor.

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR should be merged after #87 

cc @S-Dafarra

### CODE REVIEW

**Comment by S-Dafarra** [comment]
> This PR should be merged after #87
> 
> cc @S-Dafarra

And after https://github.com/robotology/unicycle-footstep-planner/pull/41

**Comment by S-Dafarra** [comment]
@GiulioRomualdi I cannot add you as a reviewer, but please take a look at the code

**Review by isorrentino — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
I think we can merge it

**Review by isorrentino — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
Let's wait for #87 before merging this PR

**Comment by S-Dafarra** [comment]
I just realized that the reason why the robot was not walking straight when using the ``feetYawDelta``, is because the reference coming from the joystick is translated in the "robot frame" by using the foot orientation, while instead it should use the unicycle angle. I will try to fix it, so this is an additional blocking point for this PR.

**Comment by S-Dafarra** [comment]
> I just realized that the reason why the robot was not walking straight when using the `feetYawDelta`, is because the reference coming from the joystick is translated in the "robot frame" by using the foot orientation, while instead it should use the unicycle angle. I will try to fix it, so this is an additional blocking point for this PR.

Done in https://github.com/robotology/walking-controllers/pull/89/commits/dc33e9ad3756136b7038332a97976dd6bb66f017

**Comment by GiulioRomualdi** [comment]
Since  #87 contains several rebase, I'm fixing the commits

**Comment by GiulioRomualdi** [comment]
@S-Dafarra let me know if we can merge it

**Comment by S-Dafarra** [comment]
I think so. The main structural change has been introduced in https://github.com/robotology/walking-controllers/pull/89/commits/86792c8d570590593c9bd3223fcfa773170f3816, where the logic to transform the references from a local frame to a global frame has been moved in a single place in the ``computeThread``. If it is ok for you we can proceed.

**Comment by GiulioRomualdi** [comment]
@S-Dafarra seems ok 😃

**Pull request merged**
