### PR TITLE
Paris and minister demo

### PR DESCRIPTION
**Pull request by S-Dafarra**
This includes the changes of the [``minister_demo`` branch ](https://github.com/robotology/walking-controllers/tree/minister-demo), rebased on top of ``master``.

### CODE REVIEW

**Comment by S-Dafarra** [comment]
Actually, this is blocked by https://github.com/robotology/unicycle-footstep-planner/pull/51

**Comment by S-Dafarra** [comment]
This has been tested on the robot

**Review by isorrentino — APPROVED** [review]

**Comment by S-Dafarra** [comment]
Since https://github.com/robotology/unicycle-footstep-planner/pull/51 has been merged, I guess we can proceed with this one too @GiulioRomualdi

**Comment by S-Dafarra** [comment]
@GiulioRomualdi I would proceed with the merge if you agree

**Comment by S-Dafarra** [comment]
> @GiulioRomualdi I would proceed with the merge if you agree

Friendly ping @GiulioRomualdi

**Comment by S-Dafarra** [comment]
> > @GiulioRomualdi I would proceed with the merge if you agree
> 
> Friendly ping @GiulioRomualdi

Friendly ping @GiulioRomualdi

**Review by GiulioRomualdi — APPROVED** [review]

**Pull request merged**
