### PR TITLE
Adding files for walking autonomous on SN000

### PR DESCRIPTION
**Pull request by S-Dafarra**
cc @carloscp3009

### CODE REVIEW

**Comment by S-Dafarra** [comment]
@GiulioRomualdi friendly ping

**Comment by S-Dafarra** [comment]
I borrowed two commits from https://github.com/robotology/walking-controllers/pull/194:
- https://github.com/robotology/walking-controllers/pull/193/commits/f9c8e93cf39bb0c679fe2d2819ea5dc4ee584ce9
- https://github.com/robotology/walking-controllers/pull/193/commits/bc0b6cf9bbdc1ca71960f175dafb4fa1ac69778e

**Comment by GiulioRomualdi** [comment]
> I borrowed two commits from #194:
> 
> * [f9c8e93](https://github.com/robotology/walking-controllers/commit/f9c8e93cf39bb0c679fe2d2819ea5dc4ee584ce9)
> * [bc0b6cf](https://github.com/robotology/walking-controllers/commit/bc0b6cf9bbdc1ca71960f175dafb4fa1ac69778e)

I would remove these two commits and keep them in one #194

**Comment by S-Dafarra** [comment]
> > I borrowed two commits from #194:
> > 
> > * [f9c8e93](https://github.com/robotology/walking-controllers/commit/f9c8e93cf39bb0c679fe2d2819ea5dc4ee584ce9)
> > * [bc0b6cf](https://github.com/robotology/walking-controllers/commit/bc0b6cf9bbdc1ca71960f175dafb4fa1ac69778e)
> 
> I would remove these two commits and keep them in one #194

Those are extremely useful for autonomy too. What is the plan for #194?

**Comment by S-Dafarra** [comment]
I see. The commit(s) I took instead are quite plain and simple. My proposal then would be to merge this, and then rebase #194 on top of master afterward (something I can take care of). Does it make sense?

**Pull request merged**
